accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
	path('signup/', SignUpView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prison/', include("prison.urls")),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include("django.contrib.auth.urls")),
]

prison/urls.py
from django.urls import path
from . import views

app_name = 'prison'
urlpatterns = [
	# path(route, view, kwargs, name) is the format

	path('', views.index, name='home'),
	path('show', views.show, name='show'),
	path('insert', views.insert, name='insert'),
	path('destroy/<int:prisoner_id>', views.destroy, name='destroy'),
	path('edit/<int:prisoner_id>', views.edit, name='edit'),

	path('<int:prisoner_id>/visitors', views.show_visitors, name='visitors'),
	path('<int:prisoner_id>/visitors/<int:visitor_id>/remove', views.remove_visitor_from_prisoner, name='remove_visitor_from_prisoner'),
	path('<int:prisoner_id>/visitors/insert', views.insert_visitor_to_prisoner, name='insert_visitor_to_prisoner'),
]

accounts/models.py
from django.db import models

# Create your models here.

prison/models.py
from django.db import models

class Prisoner(models.Model):
	name = models.CharField(max_length = 100)
	start_date = models.DateTimeField(
		'start date of prison sentence',
		)

	def __str__(self): 
		return self.name

class Visitor(models.Model):
	visitor_id = models.AutoField(primary_key=True)
	visitor_name = models.CharField(max_length = 100)
	associated_prisoners = models.ManyToManyField('prison.Prisoner')

	TYPES_OF_VISITORS = {
		('L', 'Lawyer'),
		('F', 'Family or Friends'),
		('O', 'Other')
		}
	visitor_type = models.CharField(
		max_length = 1, 
		choices = TYPES_OF_VISITORS,
		default = 'O'
		) # Move this field to through

	def __str__(self): 
		return f'{self.visitor_id}: {self.visitor_name}'

prison/forms.py
from django import forms
from .models import Prisoner, Visitor
from django.db.models import Q

class PrisonerForm(forms.ModelForm):
	class Meta:
		model = Prisoner 
		fields = ["name", "start_date"]

class ExistingVisitorForm(forms.Form):
	def __init__(self, applicable_visitors, *args, **kwargs):
		super(ExistingVisitorForm, self).__init__(*args, **kwargs)

		# Only show visitors that aren't already associated with the prisoner
		self.fields['visitor'] = forms.ModelChoiceField(queryset=applicable_visitors)

	# def save(self, commit=True):
	# 	# user = super().save(commit=False)
	# 	self.cleaned_data['associated_prisoners'] = 

	# 	if commit:
	# 		user.save()

	# 	return user

class NewVisitorForm(forms.ModelForm):
	class Meta:
		model = Visitor
		fields = ["visitor_name", "visitor_type"]

	def save(self, commit=True, default_associated_prisoner=None):
		if not commit:
			raise NotImplementedError("New visitor instance needs to be saved.")

		visitor = super().save()
		if default_associated_prisoner:
			visitor.associated_prisoners.add(default_associated_prisoner)
		visitor.save()
		return visitor

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

prison/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from .models import Prisoner as Pr, Visitor
from .forms import *
from accounts.decorators import my_login_required, allowed_users

@my_login_required
def index(request):
	is_police = False
	is_neither = False

	if request.user.groups.exists():
		# Assuming user is only in one group
		if 'Police' == request.user.groups.all()[0].name: 
			is_police = True
	else:
		is_neither = True

	return render(
		request, 
		'prison/index.html', 
		{'is_police': is_police, 'is_neither': is_neither}
		)

@my_login_required
@allowed_users(['DataManager', 'Police'])
def show(request):
	prisoners = Pr.objects.all()
	is_datamanager = (request.user.groups.all()[0].name == 'DataManager') # Only DM should be able to view certain options

	return render(
		request, 
		'prison/show.html', 
		{'prisoners': prisoners, 'is_datamanager': is_datamanager}
		)

@my_login_required
@allowed_users(['DataManager'])
def insert(request):
	if request.method == 'GET':
		form = PrisonerForm()

	elif request.method == 'POST':
		form = PrisonerForm(request.POST)
		if form.is_valid():
			form.save() 
			return redirect('prison:show')

	return render(
		request,
		'prison/insert.html',
		{'form': form}
		)

@my_login_required
@allowed_users(['DataManager'])
def destroy(request, prisoner_id):
	prisoner = get_object_or_404(Pr, id=prisoner_id)

	if request.method == 'GET':
		return render(
			request,
			'prison/delete.html',
			{'prisoner': prisoner}
			)
	elif request.method == 'POST':
		prisoner.delete()
		#TODO Confirm delete
		#TODO Remove visitors from the prisoner before deleting prisoner
		return redirect('prison:show')

@my_login_required
@allowed_users(['DataManager'])
def edit(request, prisoner_id):
	prisoner = get_object_or_404(Pr, id=prisoner_id)
	form = PrisonerForm(request.POST or None, instance = prisoner)

	if request.method == 'POST':
		if form.is_valid():
			form.save() 
			return redirect('prison:show')

	return render(
		request,
		'prison/edit.html',
		{'prisoner': prisoner, 'form': form}
	)


@my_login_required
@allowed_users(['Police', 'DataManager'])
def show_visitors(request, prisoner_id):
	'''
	If you go to the url /prison/destroy/10, then
	the prisoner with id 10 will be deleted
	and you will be redirected to /prison/show
	'''

	prisoner = get_object_or_404(Pr, id=prisoner_id)
	visitors = prisoner.visitor_set.all()

	is_datamanager = (request.user.groups.all()[0].name == 'DataManager')

	return render(
		request,
		'prison/show_visitors.html',
		{'prisoner': prisoner, 'visitors': visitors, 'is_datamanager': is_datamanager}
	)

	
@my_login_required
@allowed_users(['DataManager'])
def insert_visitor_to_prisoner(request, prisoner_id):

	prisoner = get_object_or_404(Pr, id=prisoner_id)

	inapplicable_visitors = prisoner.visitor_set.all()
	applicable_visitors = Visitor.objects.exclude(visitor_id__in=inapplicable_visitors)
	ev_form = ExistingVisitorForm(applicable_visitors, request.POST or None)
	
	nv_form = NewVisitorForm(request.POST or None)
	
	if request.method == 'POST':
		if ev_form.is_valid():
			visitor = ev_form.cleaned_data['visitor']
			visitor.associated_prisoners.add(prisoner)
			visitor.save()
		elif nv_form.is_valid():
			nv_form.save(commit=True, default_associated_prisoner=prisoner)
			
		return redirect('prison:visitors', prisoner_id)

	return render(
		request,
		'prison/insert_visitor_to_prisoner.html',
		{'prisoner': prisoner, 'ev_form': ev_form, 'nv_form': nv_form}
	)
	
@my_login_required
@allowed_users(['DataManager'])
def remove_visitor_from_prisoner(request, prisoner_id, visitor_id):
	'''
	Given a prisoner and a visitor who visits that prisoner, 
	dissociate both of them and delete the visitor if they do not visit any more prisoners.
	'''

	prisoner = get_object_or_404(Pr, id=prisoner_id)

	# In case visitor doesn't actually visit the prisoner
	try:
		visitor = prisoner.visitor_set.get(visitor_id=visitor_id)
	except Visitor.DoesNotExist:
		raise Http404('Visitor and prisoner did not match.')
	
	if request.method == 'GET':
		return render(
			request,
			'prison/remove_visitor_from_prisoner.html',
			{'prisoner':prisoner, 'visitor':visitor,}
			)
	elif request.method == 'POST':
		# Dissociate visitor and prisoner
		visitor.associated_prisoners.remove(prisoner)
		visitor.save()

		# Delete visitor if visitor is not connected to any prisoner
		if not visitor.associated_prisoners.all():
			visitor.delete()

		# return HttpResponseRedirect(reverse('prison:visitors', prisoner_id))
		return redirect('prison:visitors', prisoner_id)

prison/templates/prison/delete.html
{% extends "base.html" %}
{% block title %}
	Confirm Delete
{% endblock title %}

{% block form_style %}
	
{% endblock form_style %}

{% block content %}
<h3>Confirm Delete</h3>
<p>Are you sure you want to delete {{ prisoner }}?</p>
<form method="POST" class="post-form">  
    {% csrf_token %}
    <input type="submit" value="Yes">
    <input type="submit" value="Cancel" onclick="window.location='{% url 'prison:show' %}' ; return false;" >
</form>  
	
{% endblock content %}

prison/templates/prison/edit.html
{% extends "base.html" %}
{% block title %}
	Edit Prisoner
{% endblock title %}

{% block content %}
<h3>Edit Prisoner {{ prisoner }}</h3>
	<form method="POST">
	    {% csrf_token %}  
	    {{ form.as_p }}
	    <input type="submit" value="Submit">
	    <br><br>
	</form>  

	<p><a href="{% url 'prison:show' %}">Back to list of prisoners.</a></p>
{% endblock content %}

prison/templates/prison/index.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock title %}
{% block content %}
	<h3>Homepage</h3>
	{% if is_neither == True %}
		<p>
			Only data managers and police officers are allowed to access this system.<br>
			Please contact the superuser to gain access if you are eligible.
		</p>
	{% elif is_police == True %}
		<ul>
		<li> <a href="{% url 'prison:show' %}">View Prisoners</a> </li>
		</ul>
	{% else %}
		<ul>
		<li> <a href="{% url 'prison:show' %}">View Prisoners</a> </li>
		<li> <a href="{% url 'prison:insert' %}">Insert Prisoner</a> </li>
		</ul>
	{% endif %}
{% endblock content %}

prison/templates/prison/insert.html
{% extends "base.html" %}
{% block title %}
	Insert Prisoner
{% endblock title %}

{% block content %}
	<h3>Insert Prisoner</h3>
	<form method="POST" class="post-form" action="insert">  
	    {% csrf_token %}  
	    {{form.as_p}}
	    <input type="submit" value="Submit">
	    <br><br>
	</form>  

	<p><a href="{% url 'prison:home' %}">Back to homepage.</a></p>

{% endblock content %}

prison/templates/prison/insert_visitor_to_prisoner.html
{% extends "base.html" %}

{% block title %}
	Insert Visitor
{% endblock title %}
{% block content %}
	<h3>Insert Visitor to Prisoner {{ prisoner }}</h3>
	<h4>Create a new visitor and add them to this prisoner:</h4>
	<form method="POST" class="post-form" action="insert" id="new-visitor-form">  
	    {% csrf_token %}  
	 	{{nv_form.as_p}}
	    <input type="submit" value="Submit" form="new-visitor-form">
	</form>  
	<br><br>
	<h4>OR choose from a visitor in the database:</h4>
	<form method="POST" class="post-form" action="insert" id="existing-visitor-form">  
	    {% csrf_token %}  
	    {{ev_form.as_p}}
	    <input type="submit" value="Submit" form="existing-visitor-form">
	</form>  
{% endblock content %}

prison/templates/prison/remove_visitor_from_prisoner.html
{% extends "base.html" %}
{% block title %}
	Confirm Visitor Removal
{% endblock title %}

{% block form_style %}
	
{% endblock form_style %}

{% block content %}
	<h3>Confirm Visitor Removal</h3>
	<p>Are you sure you want to remove "{{ visitor }}" from {{ prisoner }}?</p>
	<form method="POST" class="post-form">  
	    {% csrf_token %}
	    <input type="submit" value="Yes">
	    <input type="submit" value="Cancel" onclick="window.location='{% url 'prison:visitors' prisoner.id %}' ; return false;" >
	</form>  

{% endblock content %}

prison/templates/prison/show.html
{% extends "base.html" %}
{% block title %}
	Prisoner Records
{% endblock title %}	
{% block content %}
	<h3>List of Prisoners in Database:</h3>
		{% if prisoners %}
		<table>
		<tr>
			<th>Sno.</th>
			<th>Name</th>
			<th>Start Date</th>
			{% if is_datamanager %}
			<th>Edit</th>
			<th>Destroy</th>
			{% endif %}
			<th>Visitors</th>
		</tr>
		{% for prisoner in prisoners %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{prisoner.name}}</td>
			<td>{{prisoner.start_date}}</td>
			{% if is_datamanager %}
			<td>
				<a href="{% url 'prison:edit' prisoner.id %}">
					Edit
				</a>
			</td>
			<td>
				<a href="{% url 'prison:destroy' prisoner.id %}">
					Destroy
				</a>
			</td>
			{% endif %}
			<td>
				<a href="{% url 'prison:visitors' prisoner.id %}">
					Visitors
				</a>
			</td>
		</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>No prisoners currently.</p>
	{% endif %}
	<p><a href="{% url 'prison:home' %}">Back to homepage.</a></p>


{% endblock content %}

prison/templates/prison/show_visitors.html
{% extends "base.html" %}
{% block title %}
	Visitors for Prisoner {{prisoner}}
{% endblock title %}
{% block content %}
	<h3>Visitors for Prisoner {{prisoner}}:</h3>
		{% if visitors %}
		<table>
		<tr>
			<th>Sno.</th>
			<th>ID</th>
			<th>Name</th>
			<th>Type</th>
			{% if is_datamanager %}
				<th>Remove</th>
			{% endif %}
		</tr>
		{% for visitor in visitors %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{visitor.visitor_id}}</td>
			<td>{{visitor.visitor_name}}</td>
			<td>{{visitor.get_visitor_type_display}}</td>
			{% if is_datamanager %}
				<td><a href="{% url 'prison:remove_visitor_from_prisoner' prisoner.id visitor.visitor_id %}"</a>Remove</td>
			{% endif %}

		</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>The prisoner, {{prisoner}}, has no visitors currently.</p>
	{% endif %}
	<br>
	{% if is_datamanager %}
		<p><a href="{% url 'prison:insert_visitor_to_prisoner' prisoner.id %}">Insert new visitor.</a></p>
	{% endif %}
	<p><a href="{% url 'prison:show' %}">Back to list of prisoners.</a></p>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>

<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<style>
{% block table_style %}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
{% endblock table_style %}

{% block form_style %}
  
/* For forms https://www.w3schools.com/css/tryit.asp?filename=trycss_form_responsive*/
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  float: left;
}

input[type=submit]:hover {
  background-color: #45a049;
}
{% endblock form_style %}
</style>

{% block head %}
	<header style="border-style: none; position:fixed; top: 10px; right: 10px;">
			Logged in as {{ user }}. <a href="{% url 'logout' %}">Logout here.</a>
	</header> 
{% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
	Home
{% endblock title %}

{% block content %}
	{% if user.is_authenticated %}
		Hi {{ user.username }}
		<p>
			<a href="{% url 'logout' %}">Log Out</a>
		</p>
	{% else %}
		<p> Not logged it. </p>
		<a href="{% url 'login' %}">Log In</a>
	{% endif %}
{% endblock content %}